//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareproject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class covidTable
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<long> AdharCard { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string Place { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Booking Date and Time")]
  
        
        public Nullable<System.DateTime> BookDateandTime { get; set; }
    }
}
