//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string Name { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Specialist { get; set; }
        public int Fees { get; set; }
    }
}
