//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fillinfo
    {
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Diseases { get; set; }
        public string Symptoms { get; set; }
        public string AffectedArea { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
