//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareproject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RequestAppointment1
    {
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "please enter the diseases")]
        public string Diseases { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "please enter the symptoms")]
        public string Symptoms { get; set; }
        public string AffectedArea { get; set; }
        public int id { get; set; }
        [DataType(DataType.Date)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "please schedule the time")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> BookTime { get; set; }
    }
}
